//
//  Static.swift
//  Jebreed
//
//  Created by Jevon Levin on 23/05/23.
//

import Foundation

let funFacts = [
    "default" : "",
    "Silky Terrier": "Silky Terriers have a luxurious, flowing coat that requires regular grooming.",
    "Scottish Deerhound": "Scottish Deerhounds are one of the tallest dog breeds in the world.",
    "Chesapeake Bay Retriever": "Chesapeake Bay Retrievers have a waterproof coat that helps them swim in cold water.",
    "Ibizan Hound": "Ibizan Hounds are excellent jumpers and can clear impressive heights.",
    "Wire Haired Fox Terrier": "Wire Haired Fox Terriers were bred to hunt small game like rats and foxes.",
    "Saluki": "Salukis are one of the oldest known dog breeds, dating back thousands of years.",
    "Cocker Spaniel": "Cocker Spaniels were originally bred for hunting woodcock birds.",
    "Schipperke": "Schipperkes are nicknamed 'Little Black Devils' due to their mischievous nature.",
    "Borzoi": "Borzois, also known as Russian Wolfhounds, were bred to hunt wolves in Russia.",
    "Pembroke": "Pembrokes were traditionally used as herding dogs and were associated with woodland fairies.",
    "Komondor": "Komondors have a distinctive corded coat that resembles dreadlocks.",
    "Staffordshire Bull Terrier": "Staffordshire Bull Terriers are known for their loving and friendly nature.",
    "Standard Poodle": "Standard Poodles were originally bred as water retrievers and are highly skilled swimmers.",
    "Eskimo Dog": "Eskimo Dogs, or American Eskimo Dogs, are descendants of European spitz-type dogs.",
    "English Foxhound": "English Foxhounds have an excellent sense of smell and are adept at tracking scents.",
    "Golden Retriever": "Golden Retrievers are renowned for their friendly and gentle temperament.",
    "Sealyham Terrier": "Sealyham Terriers were named after the estate where they were developed in Wales.",
    "Japanese Spaniel": "Japanese Spaniels, or Japanese Chins, were treasured companions of Japanese nobility.",
    "Miniature Schnauzer": "Miniature Schnauzers have a charming appearance with bushy eyebrows and beard.",
    "Malamute": "Alaskan Malamutes are one of the oldest Arctic sled dog breeds.",
    "Malinois": "Malinois are highly versatile working dogs often used in police and military roles.",
    "Pekinese": "Pekingese were companions to Chinese imperial dynasties and were considered sacred.",
    "Giant Schnauzer": "Giant Schnauzers are a larger and more powerful version of the Standard Schnauzer.",
    "Mexican Hairless": "Mexican Hairless dogs, or Xolos, were revered by ancient Aztecs and Mayans.",
    "Doberman": "Doberman Pinschers were developed for protection by a German tax collector.",
    "Standard Schnauzer": "Standard Schnauzers have a distinctive 'beard' and are the oldest Schnauzer breed.",
    "Dhole": "Dholes are highly social and cooperative hunters, living in packs.",
    "German Shepherd": "German Shepherds are known for their intelligence, loyalty, and versatility in various roles.",
    "Bouvier Des Flandres": "Bouviers Des Flandres are powerful herding dogs with a distinctive rugged appearance.",
    "Siberian Husky": "Siberian Huskies have thick double coats that keep them warm in cold climates.",
    "Norwich Terrier": "Norwich Terriers are small but fearless and make excellent companions.",
    "Irish Terrier": "Irish Terriers are known for their courageous and spunky personalities.",
    "Norfolk Terrier": "Norfolk Terriers have a wiry, weather-resistant coat and a playful, friendly nature.",
    "Saint Bernard": "Saint Bernards are large and gentle dogs, historically used for mountain rescue.",
    "Border Terrier": "Border Terriers are energetic, affectionate, and excel in various dog sports.",
    "Briard": "Briards, or Berger de Brie, are herding dogs with a distinctive shaggy coat.",
    "Tibetan Mastiff": "Tibetan Mastiffs are large and protective dogs with a long history in Tibet.",
    "Bull Mastiff": "Bull Mastiffs were originally bred to guard estates and are powerful and protective.",
    "Maltese Dog": "Maltese Dogs have a luxurious white coat and were treasured by ancient civilizations.",
    "Kerry Blue Terrier": "Kerry Blue Terriers are versatile dogs known for their unique blue-gray coat.",
    "Kuvasz": "Kuvasz dogs are ancient Hungarian guardians known for their loyalty and fearlessness.",
    "Greater Swiss Mountain Dog": "Greater Swiss Mountain Dogs are strong and sturdy working dogs from Switzerland.",
    "Lakeland Terrier": "Lakeland Terriers are small, feisty dogs with a zest for life.",
    "Blenheim Spaniel": "Blenheim Spaniels are a color variety of the Cavalier King Charles Spaniel.",
    "Basset": "Bassets have long ears, a keen sense of smell, and a laid-back demeanor.",
    "West Highland White Terrier": "West Highland White Terriers, or Westies, are lively and confident little dogs.",
    "Chihuahua": "Chihuahuas are the smallest dog breed and are known for their sassy personalities.",
    "Border Collie": "Border Collies are highly intelligent and excel in herding and dog sports.",
    "Redbone": "Redbones are coonhounds known for their beautiful red coat and exceptional scenting ability.",
    "Irish Wolfhound": "Irish Wolfhounds are one of the tallest dog breeds and have a gentle nature.",
    "Bluetick": "Blueticks are coonhounds named for their distinctive blue ticking on their coat.",
    "Miniature Poodle": "Miniature Poodles are intelligent and versatile dogs with a hypoallergenic coat.",
    "Cardigan": "Cardigan Welsh Corgis are known for their long tail and excellent herding skills.",
    "Entlebucher": "Entlebuchers are the smallest Swiss Mountain Dogs, valued for their herding ability.",
    "Norwegian Elkhound": "Norwegian Elkhounds are ancient spitz-type dogs known for their endurance and versatility.",
    "German Short Haired Pointer": "German Shorthaired Pointers are versatile hunting dogs with a sleek coat.",
    "Bernese Mountain Dog": "Bernese Mountain Dogs are large, gentle giants with a striking tricolor coat.",
    "Papillon": "Papillons are small and elegant dogs known for their butterfly-like ears.",
    "Tibetan Terrier": "Tibetan Terriers are shaggy dogs originally bred as companions and good luck charms.",
    "Gordon Setter": "Gordon Setters are elegant and athletic bird dogs with a distinctive black and tan coat.",
    "American Staffordshire Terrier": "American Staffordshire Terriers are muscular dogs with a loyal and affectionate nature.",
    "Vizsla": "Vizslas are energetic and affectionate sporting dogs known for their stunning rust-colored coat.",
    "Kelpie": "Kelpies are Australian working dogs with exceptional herding and agility skills.",
    "Weimaraner": "Weimaraners are known for their striking gray coat and high energy levels.",
    "Miniature Pinscher": "Miniature Pinschers are small but spirited dogs with a fearless and confident attitude.",
    "Boxer": "Boxers are medium-sized, muscular dogs known for their playful and energetic nature.",
    "Chow": "Chows are ancient Chinese dogs with a distinctive lion-like appearance and a loyal temperament.",
    "Old English Sheepdog": "Old English Sheepdogs have a shaggy coat and are famously known as 'Bobtails.'",
    "Pug": "Pugs are small, wrinkled dogs with a friendly and outgoing personality.",
    "Rhodesian Ridgeback": "Rhodesian Ridgebacks have a distinctive ridge of hair along their backs.",
    "Scotch Terrier": "Scottish Terriers, or Scotties, are small and dignified dogs with a distinctive beard.",
    "Shih Tzu": "Shih Tzus are small and affectionate companion dogs known for their luxurious coat.",
    "Affenpinscher": "Affenpinschers, also known as Monkey Dogs, are small and mischievous with a monkey-like expression.",
    "Whippet": "Whippets are sleek and fast dogs known for their incredible speed and agility.",
    "Sussex Spaniel": "Sussex Spaniels are low-energy and gentle dogs with a friendly and sociable nature.",
    "Otterhound": "Otterhounds have a unique shaggy coat and are excellent swimmers and scent trackers.",
    "Flat Coated Retriever": "Flat Coated Retrievers are versatile sporting dogs known for their glossy black coat.",
    "English Setter": "English Setters are elegant and athletic dogs known for their distinctive feathered coat.",
    "Italian Greyhound": "Italian Greyhounds are small and graceful dogs known for their sleek and slender appearance.",
    "Labrador Retriever": "Labrador Retrievers are friendly, loyal, and one of the most popular dog breeds.",
    "Collie": "Collies are intelligent and gentle herding dogs known for their loyalty and protective nature.",
    "Cairn": "Cairn Terriers are small, hardy dogs known for their wiry coat and lively personality.",
    "Rottweiler": "Rottweilers are strong and confident dogs with a protective nature.",
    "Australian Terrier": "Australian Terriers are small, sturdy dogs known for their wiry coat and playful demeanor.",
    "Toy Terrier": "Toy Terriers, or Manchester Terriers, are lively and intelligent dogs with a sleek coat.",
    "Shetland Sheepdog": "Shetland Sheepdogs, or Shelties, are intelligent and agile herding dogs.",
    "African Hunting Dog": "African Hunting Dogs, or African Wild Dogs, are highly social and cooperative hunters.",
    "Newfoundland": "Newfoundlands are large and gentle giants known for their swimming and lifesaving abilities.",
    "Walker Hound": "Walker Hounds are coonhounds known for their speed, endurance, and excellent scenting ability.",
    "Lhasa": "Lhasa Apsos are small, confident dogs with a long and flowing coat.",
    "Beagle": "Beagles are scent hounds with an excellent sense of smell and friendly disposition.",
    "Samoyed": "Samoyeds are friendly and gentle dogs known for their beautiful white and fluffy coat.",
    "Great Dane": "Great Danes are one of the tallest dog breeds and are known for their gentle nature.",
    "Airedale": "Airedales, also known as the 'King of Terriers,' are versatile and courageous dogs.",
    "Bloodhound": "Bloodhounds have an exceptional sense of smell and are often used for tracking.",
    "Irish Setter": "Irish Setters are elegant and energetic sporting dogs with a stunning mahogany coat.",
    "Keeshond": "Keeshonden are friendly and playful dogs known for their thick double coat.",
    "Dandie Dinmont": "Dandie Dinmont Terriers are small and distinctive dogs with a topknot of hair on their head.",
    "Basenji": "Basenjis are small, independent dogs known for their unique yodel-like vocalizations.",
    "Bedlington Terrier": "Bedlington Terriers have a distinctive lamb-like appearance with a curly coat.",
    "Appenzeller": "Appenzellers are Swiss herding dogs with a high energy level and a strong work ethic.",
    "Clumber": "Clumber Spaniels are heavy-boned and low-energy dogs known for their hunting skills.",
    "Toy Poodle": "Toy Poodles are intelligent and elegant dogs with a hypoallergenic curly coat.",
    "Great Pyrenees": "Great Pyrenees are large and majestic dogs with a thick white coat.",
    "English Springer": "English Springer Spaniels are versatile hunting dogs and excellent family companions.",
    "Afghan Hound": "Afghan Hounds are elegant and regal dogs known for their long and flowing coat.",
    "Brittany Spaniel": "Brittany Spaniels are energetic and agile sporting dogs known for their versatility.",
    "Welsh Springer Spaniel": "Welsh Springer Spaniels are cheerful and intelligent dogs with a silky red and white coat.",
    "Boston Bull": "Boston Bulls, or Boston Terriers, are small and friendly dogs with a distinctive tuxedo-like coat.",
    "Dingo": "Dingoes are wild dogs native to Australia with a resilient and independent nature.",
    "Soft Coated Wheaten Terrier": "Soft Coated Wheaten Terriers are friendly and affectionate dogs with a soft, wavy coat.",
    "Curly Coated Retriever": "Curly Coated Retrievers have a distinctive curly coat and are excellent swimmers.",
    "French Bulldog": "French Bulldogs are small, muscular dogs known for their unique bat-like ears.",
    "Irish Water Spaniel": "Irish Water Spaniels are versatile water retrievers with a dense, curly coat.",
    "Pomeranian": "Pomeranians are small and fluffy dogs with a proud and lively personality.",
    "Brabancon Griffon": "Brabancon Griffons are small and sturdy dogs known for their distinctive beard and mustache.",
    "Yorkshire Terrier": "Yorkshire Terriers, or Yorkies, are small and glamorous dogs with a long, silky coat.",
    "Groenendael": "Groenendaels are elegant and intelligent dogs with a long, black coat.",
    "Leonberg": "Leonbergs are large and gentle dogs with a lion-like appearance and a friendly temperament.",
    "Black And Tan Coonhound": "Black And Tan Coonhounds are skilled scent hounds with a striking black and tan coat."
]
